### ISSUE TITLE
[FEATURE REUQEST] Video Preview straight in repo

### ISSUE THREAD

**Issue by KendallDoesCoding** [Firecul/FiveM-Nurburgring#1]
Instead of linking, https://streamable.com/pmmyu why not upload the video on GitHub and link that video to the README?

**Comment by Firecul** [comment]
https://github.com/bepo13/FiveM-Nurburgring-Nordschleife-Circuit is the root fork for this project and it was just a copy from there, I haven't really put in that much effort into it personally. 
I'm going to take a look at a couple of fixes tonight though coincidentally.

**Comment by KendallDoesCoding** [comment]
> 

Ok cool. Should I close this issue tho?

**Comment by Firecul** [comment]
Yeah, I don't see a reason to change that, it's not anything that'll change much IMO.
I'm happy for the inputs though.

**Comment by KendallDoesCoding** [comment]
> Yeah, I don't see a reason to change that, it's not anything that'll change much IMO. I'm happy for the inputs though.

yeah true. Just thought of the idea to make it easier for users but yeah it's no issue clicking the link and watching the video too lol
