### ISSUE TITLE
Map is too high, shadows don't work

### ISSUE THREAD

**Issue by ghost** [Firecul/FiveM-Nurburgring#2]
I tried to relocate it using the YMAP-YBN-Mover.exe to the height of 1191 because shadows don't appear above the height of 1500 (default map height is at 2191) but fivem keeps getting stuck at preloading collisions when I launch my server. Please help.
![image_2023-01-11_111740643](https://user-images.githubusercontent.com/114300471/211753638-b7e29719-0882-4c41-a65f-291988bdb69d.png)

**Comment by Firecul** [comment]
Did you check my [Lowered Track](https://github.com/Firecul/FiveM-Nurburgring/tree/LoweredTrack) branch, already sorted it for you 👍

**Comment by ghost** [comment]
How do I install your lowered version? its less than 1MB, Do I replace something?

**Comment by Firecul** [comment]
I think I know what has happened, did you pull the LFS files or just download the zip?
I converted this repo to use Git LFS as every time I was changing anything it was massively increasing the size of the repo that needed to be downloaded each time.

**Comment by ghost** [comment]
My bad, I downloaded the zip. So how do I pull the LFS files?

**Comment by Firecul** [comment]
I just normally clone the repo, as long as you have git-lfs installed then it does it automatically

![mintty_MINGW64dNew_folderFiveM-Nurburgring](https://user-images.githubusercontent.com/34950371/214724088-8aa6eff9-50e0-4b01-af1a-4c1747550cd6.png)
![explorer_stream](https://user-images.githubusercontent.com/34950371/214724193-425e845c-37f8-43a6-9e2b-9082822f17b7.png)

**Comment by ghost** [comment]
Thank you!
